---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: test-annotations
  annotations:
    pipelinesascode.tekton.dev/on-event:  "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    # Fetch the git-clone task from hub, we are able to reference later on it
    # with taskRef and it will automatically be embedded into our pipeline.
    pipelinesascode.tekton.dev/pipeline: "https://github.com/piyush-garg/remote-task/blob/main/pipeline.yaml"
spec:
  params:
    - name: repo-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
  pipelineRef:
    name: git-clone-pipeline
  workspaces:
    - name: source
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi