---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: "piplinerun-remote-annotations"
  annotations:
    pipelinesascode.tekton.dev/target-namespace: "pac-e2e-ns-ckjh6"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/on-event: "[pull_request]"
    pipelinesascode.tekton.dev/task: "[.other-tasks/task-referenced-internally.yaml]"
    pipelinesascode.tekton.dev/task-1: "[https://github.com/piyush-garg/test-e2e-private/blob/main/test.yaml]"
    pipelinesascode.tekton.dev/task-2: "pylint"
spec:
  pipelineRef:
    name: pipeline-in-tekton-dir
