apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: print-message
  annotations:
    task.results.format: application/json
    task.results.type: roxctl-image-scan
    task.results.key: SCAN_OUTPUT
    task.output.location: logs
    task.results.container: step-rox-image-scan
    random.annotation: THIS_SHOULD_BE_HERE
  labels:
    random.label: THIS_SHOULD_ALSO_BE_HERE
spec: 
  params:
    - name: message
      type: string
      default: "no message"
  steps:
  - name: print-message
    image: registry.access.redhat.com/ubi8-minimal@sha256:d8b81a38b5ad9694742ea03159d3217cd2dde3997b1ee53bbb53c33dd67be7b7
    script: |
      #!/usr/bin/env bash 
      echo "Hello $(params.message)"  
     
