apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: pac-pipeline-annotation 
  annotations:
    pipelinesascode.tekton.dev/on-event: "[pull_request, push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]" 
    pipelinesascode.tekton.dev/pipeline: "https://raw.githubusercontent.com/jduimovich/pac-test/main/.tekton/pipeline.yaml"
    pipelinesascode.tekton.dev/task-0: "https://raw.githubusercontent.com/jduimovich/pac-test/main/.tekton/task.yaml"
spec: 
  params:
  - name: message
    value: "Hello"
  pipelineRef:
    name: pac-pipeline
